import Stripe from "stripe";

// Lazy-load Stripe to avoid initialization errors during build
let stripeInstance: Stripe | null = null;

export function getStripe(): Stripe {
    if (!stripeInstance) {
        if (!process.env.STRIPE_SECRET_KEY) {
            throw new Error("STRIPE_SECRET_KEY is not configured");
        }
        stripeInstance = new Stripe(process.env.STRIPE_SECRET_KEY);
    }
    return stripeInstance;
}

// Legacy export for backward compatibility
export const stripe = {
    checkout: {
        sessions: {
            create: async (params: Stripe.Checkout.SessionCreateParams) => getStripe().checkout.sessions.create(params),
            retrieve: async (id: string, options?: Stripe.Checkout.SessionRetrieveParams) => getStripe().checkout.sessions.retrieve(id, options),
        }
    },
    webhooks: {
        constructEvent: (payload: string, header: string, secret: string) => getStripe().webhooks.constructEvent(payload, header, secret),
    }
};

// Product configuration
export const STRIPE_PRODUCTS = {
    pro_monthly: {
        name: "RACIO Pro Monthly",
        priceId: process.env.STRIPE_PRICE_PRO_MONTHLY || "",
        mode: "subscription" as const,
    },
    pro_yearly: {
        name: "RACIO Pro Yearly",
        priceId: process.env.STRIPE_PRICE_PRO_YEARLY || "",
        mode: "subscription" as const,
    },
    lifetime: {
        name: "RACIO Lifetime",
        priceId: process.env.STRIPE_PRICE_LIFETIME || "",
        mode: "payment" as const,
    },
};

export type PlanType = keyof typeof STRIPE_PRODUCTS;

// ============================================================================
// LICENSE MANAGEMENT — Now handled by Lemon Squeezy License API
// ============================================================================
//
// License keys are generated by Lemon Squeezy when a user purchases.
// Validation happens via POST to /v1/licenses/validate on LS API.
// No local storage or database needed.
//
// See: src/app/api/license/validate/route.ts
// ============================================================================
