import { NextRequest, NextResponse } from "next/server";

/**
 * Checkout Success Callback
 * 
 * This endpoint handles redirects after payment completion.
 * With Lemon Squeezy, checkout happens on their hosted page.
 * License keys are generated by Lemon Squeezy and sent via email.
 * 
 * This route simply redirects to the success page with the plan type.
 */
export async function GET(request: NextRequest) {
    const searchParams = request.nextUrl.searchParams;
    const plan = searchParams.get("plan") || "pro";
    const license = searchParams.get("license") || "";

    // Redirect to success page
    const baseUrl = process.env.NEXT_PUBLIC_URL || request.nextUrl.origin;
    const successUrl = new URL(`/success?plan=${plan}${license ? `&license=${license}` : ""}`, baseUrl);

    return NextResponse.redirect(successUrl);
}
